{- | Defining the hedge algebra generated by Hgen module.
 | -}
{-#LANGUAGE TemplateHaskell#-}
module Hedgen.Ahedge (
        Hedge(..),
        module HedgeClass,
) 
where
import Hedgen.Hgen
import HedgeClass
import Language.Haskell.TH
import Language.Haskell.TH.Syntax
 
{-data Hedge = Possibly | Very | More | Less deriving (Eq, Show, Enum, Read)

instance (Ha Hedge) where
        posLs = [Very, More]
        posRel = [(Very,More), (Very,Less), (More,Very), (Very,Very), (More, More)]

--Eq Hedge = default-}

-- |Generating the type Hedge:
q

-- |Ord instance definition for Hedge
instance Ord Hedge where
        compare = compare' 

--instace Show Hedge = default

----------------------------------------------------
----------------------------------------------------

